import {useEffect,useRef,useState} from 'react';
import * as THREE from 'three';
import {OrbitControls} from 'three/addons/controls/OrbitControls.js';
import {RoomEnvironment} from 'three/addons/environments/RoomEnvironment.js';

function labelTexture(kind){
 const canvas=document.createElement('canvas');canvas.width=1024;canvas.height=1024;const c=canvas.getContext('2d');
 if(kind==='coffee'){c.fillStyle='#fff0d8';c.fillRect(0,0,1024,1024);c.textAlign='center';c.fillStyle='#121212';c.font='900 100px Arial';c.fillText('WEB',512,435);c.fillText('ROAST',512,535);c.font='22px Arial';c.fillText('F U E L   Y O U R   S T O R Y',512,595);c.fillStyle='#e50914';c.fillRect(494,655,36,7)}
 else{c.fillStyle='#14130f';c.fillRect(0,0,1024,1024);c.translate(512,512);for(let i=0;i<60;i++){c.save();c.rotate(i*Math.PI/30);c.fillStyle=i%5===0?'#d9b378':'#867452';c.fillRect(i%5===0?-5:-2,-450,i%5===0?10:4,i%5===0?57:17);c.restore()}c.fillStyle='#d6b681';c.textAlign='center';c.font='46px Georgia';c.fillText('S O L A R A',0,-155);c.font='18px Arial';c.fillText('A T E L I E R',0,-117);c.beginPath();c.arc(0,-280,25,0,Math.PI*2);c.fill();c.font='18px Arial';c.fillStyle='#877b68';c.fillText('SWISS MOVEMENT',0,310)}
 const t=new THREE.CanvasTexture(canvas);t.colorSpace=THREE.SRGBColorSpace;return t;
}
function leatherTexture(){const canvas=document.createElement('canvas');canvas.width=128;canvas.height=128;const c=canvas.getContext('2d');let seed=41;for(let y=0;y<128;y++)for(let x=0;x<128;x++){seed=(seed*16807)%2147483647;const n=25+(seed%35);c.fillStyle=`rgb(${n},${n},${n})`;c.fillRect(x,y,1,1)}const t=new THREE.CanvasTexture(canvas);t.wrapS=t.wrapT=THREE.RepeatWrapping;t.repeat.set(2,8);return t}
function makeModel(kind){const group=new THREE.Group(),parts=[],materials=[];const add=(geo,mat,pos=[0,0,0],parent=group)=>{const m=new THREE.Mesh(geo,mat);m.position.set(...pos);m.castShadow=true;m.receiveShadow=true;parent.add(m);return m};const material=(color,metalness=0,roughness=.5)=>new THREE.MeshStandardMaterial({color,metalness,roughness});let finish,second;
 if(kind==='coffee'){
 finish=material('#fff0d8',0,.82);finish.map=labelTexture(kind);materials.push(finish);const cup=add(new THREE.CylinderGeometry(.91,.68,2.5,96,1,true),finish);cup.rotation.y=Math.PI;add(new THREE.CylinderGeometry(.68,.68,.06,64),material('#e5d2b4'),[0,-1.25,0]);const lid=new THREE.Group();lid.position.y=1.25;group.add(lid);const black=material('#151515',.1,.25);add(new THREE.CylinderGeometry(1.02,1.01,.13,96),black,[0,0,0],lid);add(new THREE.CylinderGeometry(.92,.99,.21,96),black,[0,.16,0],lid);add(new THREE.CylinderGeometry(.88,.92,.06,96),black,[0,.30,0],lid);const lip=add(new THREE.TorusGeometry(.95,.035,12,96),black,[0,.08,0],lid);lip.rotation.x=Math.PI/2;const sip=add(new THREE.CapsuleGeometry(.045,.22,4,12),material('#030303'),[0,.34,.7],lid);sip.rotation.z=Math.PI/2;parts.push({mesh:lid,base:1.25,axis:'y',offset:.9});
 const beanMat=material('#552812',.1,.35);for(let i=0;i<13;i++){const a=i*Math.PI*2/13;const bean=add(new THREE.SphereGeometry(.16,16,12),beanMat,[Math.cos(a)*1.75,Math.sin(a*2)*1.8,Math.sin(a)*1.75]);bean.scale.set(.72,1.3,.7);bean.rotation.set(a,.5,a);const seam=add(new THREE.CapsuleGeometry(.014,.2,2,6),material('#1a0b05'),[0,0,.105],bean);seam.rotation.z=.22}group.rotation.z=-.13;
 }else{
 finish=material('#b58b50',.92,.27);materials.push(finish);const caseMesh=add(new THREE.CylinderGeometry(1.1,1.1,.29,96),finish);caseMesh.rotation.x=Math.PI/2;const back=add(new THREE.CylinderGeometry(.98,.98,.07,64),finish,[0,0,-.18]);back.rotation.x=Math.PI/2;
 const dialMat=material('#ffffff',.12,.64);dialMat.map=labelTexture('watch');const face=add(new THREE.CircleGeometry(.98,96),dialMat,[0,0,.17]);const bezel=add(new THREE.TorusGeometry(1.025,.056,16,100),finish,[0,0,.19]);parts.push({mesh:bezel,base:.19,axis:'z',offset:.8},{mesh:face,base:.17,axis:'z',offset:.4});
 const hands=new THREE.Group();hands.position.z=.22;group.add(hands);const hand=(length,width,angle)=>{const pivot=new THREE.Group();hands.add(pivot);const m=add(new THREE.BoxGeometry(width,length,.025),finish,[0,length/2-.05,0],pivot);pivot.rotation.z=angle;return pivot};hand(.51,.055,.9);hand(.74,.035,-.85);second=hand(.85,.012,0);add(new THREE.SphereGeometry(.065,16,12),finish,[0,0,.035],hands);parts.push({mesh:hands,base:.22,axis:'z',offset:.6});
 const crystal=add(new THREE.CircleGeometry(1,96),new THREE.MeshPhysicalMaterial({color:'#cce8ff',transparent:true,opacity:.055,roughness:.03,metalness:.3,side:THREE.DoubleSide}),[0,0,.27]);parts.push({mesh:crystal,base:.27,axis:'z',offset:1.0});
 const crown=add(new THREE.CylinderGeometry(.16,.16,.22,32),finish,[1.19,0,0]);crown.rotation.z=Math.PI/2;for(let i=0;i<8;i++){const ring=add(new THREE.TorusGeometry(.16,.01,6,32),finish,[1.10+i*.026,0,0]);ring.rotation.y=Math.PI/2}
 const leather=material('#21170f',0,.88);leather.bumpMap=leatherTexture();leather.bumpScale=.03;const verts=[],uv=[],indices=[];const n=100;for(let i=0;i<=n;i++){const a=i/n*Math.PI*2;for(let side=0;side<2;side++){verts.push(side?.45:-.45,Math.cos(a)*1.75,Math.sin(a)*.9-.85);uv.push(side,i/n)}}for(let i=0;i<n;i++){const a=i*2;indices.push(a,a+1,a+2,a+1,a+3,a+2)}const band=new THREE.BufferGeometry();band.setAttribute('position',new THREE.Float32BufferAttribute(verts,3));band.setAttribute('uv',new THREE.Float32BufferAttribute(uv,2));band.setIndex(indices);band.computeVertexNormals();leather.side=THREE.DoubleSide;add(band,leather);for(const y of [-1,1])for(const x of [-.55,.55])add(new THREE.BoxGeometry(.18,.45,.25),finish,[x,y*1.06,-.015]);group.rotation.set(-.15,-.30,-.08);
 }
 return {group,parts,finish,second};}

export default function ProductScene({kind='coffee',finish='cream',explode=false}){const host=useRef(),api=useRef(),settings=useRef({finish,explode});const[playing,setPlaying]=useState(()=>!window.matchMedia('(prefers-reduced-motion: reduce)').matches),[error,setError]=useState(false);settings.current={finish,explode};
 useEffect(()=>{let renderer;const node=host.current;try{renderer=new THREE.WebGLRenderer({antialias:true,alpha:true,powerPreference:'low-power'})}catch{setError(true);return}setError(false);renderer.setPixelRatio(Math.min(devicePixelRatio,1.6));renderer.setClearColor(kind==='coffee'?0xf5e7d3:0x17130f,1);renderer.outputColorSpace=THREE.SRGBColorSpace;renderer.toneMapping=THREE.ACESFilmicToneMapping;renderer.toneMappingExposure=1.25;node.appendChild(renderer.domElement);const scene=new THREE.Scene();const camera=new THREE.PerspectiveCamera(37,1,.1,100);camera.position.set(0,kind==='coffee'?.4:0,kind==='coffee'?7.8:7.1);const controls=new OrbitControls(camera,renderer.domElement);controls.enablePan=false;controls.enableDamping=true;controls.enableZoom=false;controls.autoRotateSpeed=kind==='coffee'?1.2:.65;controls.minPolarAngle=.3;controls.maxPolarAngle=Math.PI-.3;const env=new RoomEnvironment();const pmrem=new THREE.PMREMGenerator(renderer);const envTarget=pmrem.fromScene(env,.04);scene.environment=envTarget.texture;env.dispose();scene.add(new THREE.HemisphereLight(0xfff0da,0x222033,2));const light=new THREE.DirectionalLight(0xffe6c7,4);light.position.set(3,5,4);scene.add(light);const rim=new THREE.DirectionalLight(kind==='coffee'?0x779cff:0xdba05c,3);rim.position.set(-4,1,-3);scene.add(rim);const model=makeModel(kind);scene.add(model.group);let active=true,frame=0,paused=!playing;const observer=new IntersectionObserver(([entry])=>{active=entry.isIntersecting},{threshold:.01});observer.observe(node);const resize=new ResizeObserver(()=>{const w=node.clientWidth,h=node.clientHeight;renderer.setSize(w,h);camera.aspect=w/h;camera.updateProjectionMatrix()});resize.observe(node);const colors=kind==='coffee'?{cream:'#ffffff',red:'#ef5960',blue:'#7597d8'}:{bronze:'#b58b50',steel:'#b8c1c9',onyx:'#383b41'};
 api.current={setPlaying:v=>{paused=!v},reset:()=>{controls.reset()},zoom:d=>{camera.position.multiplyScalar(d);const length=camera.position.length();if(length<4)camera.position.setLength(4);if(length>12)camera.position.setLength(12)},rotate:d=>{model.group.rotation.y+=d}};
 const animate=()=>{frame=requestAnimationFrame(animate);if(!active||document.hidden)return;controls.autoRotate=!paused;controls.update();model.finish.color.set(colors[settings.current.finish]||Object.values(colors)[0]);for(const p of model.parts){const target=p.base+(settings.current.explode?p.offset:0);p.mesh.position[p.axis]=paused?target:THREE.MathUtils.lerp(p.mesh.position[p.axis],target,.07)}if(model.second&&!paused)model.second.rotation.z=-Date.now()/1000*Math.PI/30;if(!paused)model.group.position.y=Math.sin(performance.now()*.001)*.06;renderer.render(scene,camera)};animate();return()=>{cancelAnimationFrame(frame);observer.disconnect();resize.disconnect();controls.dispose();scene.traverse(obj=>{obj.geometry?.dispose();const mats=Array.isArray(obj.material)?obj.material:[obj.material];mats.forEach(m=>{if(m){m.map?.dispose();m.bumpMap?.dispose();m.dispose()}})});envTarget.dispose();pmrem.dispose();renderer.dispose();renderer.domElement.remove();api.current=null};},[kind]);
 useEffect(()=>api.current?.setPlaying(playing),[playing]);
 return <div className={'scene-wrap '+kind}><div className="scene-stage" ref={host} tabIndex={0} role="group" aria-label={`Interactive 3D ${kind==='coffee'?'coffee cup':'watch'}. Drag to rotate or use left and right arrow keys.`} onKeyDown={e=>{if(['ArrowLeft','ArrowRight'].includes(e.key)){e.preventDefault();api.current?.rotate(e.key==='ArrowLeft'?-.15:.15)}}}/>{error&&<div className="scene-fallback"><img src="./assets/hero.png" alt={kind==='coffee'?'Web Roast coffee':'Solara watch'}/><p>3D is unavailable in this browser. Explore the product photograph instead.</p></div>}<span className="scene-caption">{error?'PRODUCT PREVIEW':'DRAG TO ROTATE · EXPLORE EVERY ANGLE'}</span><div className="scene-tools"><button onClick={()=>setPlaying(v=>!v)} aria-pressed={playing} disabled={error}>{playing?'Pause motion':'Play motion'}</button><button onClick={()=>api.current?.zoom(.85)} disabled={error} aria-label="Zoom in">+</button><button onClick={()=>api.current?.zoom(1.15)} disabled={error} aria-label="Zoom out">−</button><button onClick={()=>api.current?.reset()} disabled={error}>Reset view</button></div></div>
}
